version: "3"

services:
  hello:
    image: dockercloud/hello-world
  warp:
    build: .
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./certs/:/root/.cloudflare-warp
  warp_backup:
    build: .
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./certs/:/root/.cloudflare-warp
